name: Criar Repositório e Deploy Vercel

on:
  workflow_dispatch:
    inputs:
      tipo:
        description: 'Tipo do projeto (site ou lp)'
        required: true
        default: 'site'
      empresa:
        description: 'Nome da empresa/projeto'
        required: true
      nome_vercel:
        description: 'Nome do projeto na Vercel (define o domínio)'
        required: true
      build_command:
        description: 'Comando de build'
        required: false
        default: 'npm run build'
      output_directory:
        description: 'Diretório de output'
        required: false
        default: 'dist/spa/'
      install_command:
        description: 'Comando de instalação'
        required: false
        default: 'npm i --legacy-peer-deps'
      framework:
        description: 'Framework do projeto'
        required: true
        type: choice
        default: 'vite'
        options:
          - vite
          - angular
          - react
          - nextjs
          - other

jobs:
  criar-e-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Verificar arquivos
        run: |
          echo "Diretório atual:"
          pwd
          echo "Listagem de arquivos:"
          ls -R

      - name: Definir configurações do framework
        id: framework_config
        run: |
          # Primeiro define os defaults baseados no framework
          case "${{ github.event.inputs.framework }}" in
            "vite")
              DEFAULT_BUILD="npm run build"
              DEFAULT_OUTPUT="dist/spa/"
              DEFAULT_INSTALL="npm i --legacy-peer-deps"
              FRAMEWORK_NAME="vite"
              ;;
            "angular")
              DEFAULT_BUILD="npm run build"
              DEFAULT_OUTPUT="dist/"
              DEFAULT_INSTALL="npm ci"
              FRAMEWORK_NAME="angular"
              ;;
            "react")
              DEFAULT_BUILD="npm run build"
              DEFAULT_OUTPUT="build/"
              DEFAULT_INSTALL="npm ci"
              FRAMEWORK_NAME="create-react-app"
              ;;
            "nextjs")
              DEFAULT_BUILD="npm run build"
              DEFAULT_OUTPUT=""
              DEFAULT_INSTALL="npm ci"
              FRAMEWORK_NAME="nextjs"
              ;;
            "other")
              DEFAULT_BUILD="npm run build"
              DEFAULT_OUTPUT="dist/"
              DEFAULT_INSTALL="npm ci"
              FRAMEWORK_NAME="vite"
              ;;
          esac
          
          # Usa o input customizado se fornecido, senão usa o default
          BUILD_CMD="${{ github.event.inputs.build_command }}"
          OUTPUT_DIR="${{ github.event.inputs.output_directory }}"
          INSTALL_CMD="${{ github.event.inputs.install_command }}"
          
          echo "BUILD_COMMAND=${BUILD_CMD:-$DEFAULT_BUILD}" >> $GITHUB_OUTPUT
          echo "OUTPUT_DIRECTORY=${OUTPUT_DIR:-$DEFAULT_OUTPUT}" >> $GITHUB_OUTPUT
          echo "INSTALL_COMMAND=${INSTALL_CMD:-$DEFAULT_INSTALL}" >> $GITHUB_OUTPUT
          echo "FRAMEWORK=$FRAMEWORK_NAME" >> $GITHUB_OUTPUT
          
          # Log das configurações finais
          echo "📦 Configurações finais:"
          echo "   Build Command: ${BUILD_CMD:-$DEFAULT_BUILD}"
          echo "   Output Directory: ${OUTPUT_DIR:-$DEFAULT_OUTPUT}"
          echo "   Install Command: ${INSTALL_CMD:-$DEFAULT_INSTALL}"
          echo "   Framework: $FRAMEWORK_NAME"

      - name: Criar Repositório
        id: criar_repo
        working-directory: ${{ github.workspace }}
        run: |
          PREFIX="${{ github.event.inputs.tipo }}-${{ github.event.inputs.empresa }}"
          echo "REPO_NAME=$PREFIX" >> $GITHUB_OUTPUT
          node scripts/criar-repos.js "$PREFIX" "${{ github.event.inputs.tipo }}"
        env:
          GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}

      - name: Aguardar repositório ficar disponível
        run: sleep 15

      - name: Criar projeto na Vercel
        id: vercel_deploy
        uses: actions/github-script@v7
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        with:
          script: |
            const repoName = '${{ steps.criar_repo.outputs.REPO_NAME }}';
            const vercelProjectName = '${{ github.event.inputs.nome_vercel }}';
            const repoFullName = `${{ github.repository_owner }}/${repoName}`;
            
            // Configurações dinâmicas baseadas no framework escolhido
            const buildCommand = '${{ steps.framework_config.outputs.BUILD_COMMAND }}';
            const outputDirectory = '${{ steps.framework_config.outputs.OUTPUT_DIRECTORY }}';
            const installCommand = '${{ steps.framework_config.outputs.INSTALL_COMMAND }}';
            const framework = '${{ steps.framework_config.outputs.FRAMEWORK }}';
            
            const projectConfig = {
              name: vercelProjectName,
              gitRepository: {
                type: 'github',
                repo: repoFullName
              },
              buildCommand: buildCommand,
              installCommand: installCommand,
              framework: framework,
              publicSource: false
            };
            
            // Só adiciona outputDirectory se não estiver vazio (Next.js não precisa)
            if (outputDirectory) {
              projectConfig.outputDirectory = outputDirectory;
            }
            
            console.log('Criando projeto Vercel com config:', JSON.stringify(projectConfig, null, 2));
            
            // Criar projeto na Vercel
            const vercelResponse = await fetch('https://api.vercel.com/v9/projects', {
              method: 'POST',
              headers: {
                'Authorization': `Bearer ${process.env.VERCEL_TOKEN}`,
                'Content-Type': 'application/json',
                ...(process.env.VERCEL_ORG_ID && { 'X-Vercel-Team-Id': process.env.VERCEL_ORG_ID })
              },
              body: JSON.stringify(projectConfig)
            });
            
            if (!vercelResponse.ok) {
              const error = await vercelResponse.text();
              console.error('Resposta da Vercel:', error);
              throw new Error(`Erro ao criar projeto Vercel (${vercelResponse.status}): ${error}`);
            }
            
            const vercelProject = await vercelResponse.json();
            
            console.log(`✅ Projeto Vercel criado: ${vercelProject.name}`);
            console.log(`🔗 URL do projeto: https://${vercelProjectName}.vercel.app`);
            
            core.setOutput('vercel_url', `https://${vercelProjectName}.vercel.app`);
            core.setOutput('vercel_project_id', vercelProject.id);
            core.setOutput('vercel_name', vercelProject.name);
            
            return vercelProject;

      - name: Configurar branch de produção na Vercel
        uses: actions/github-script@v7
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        with:
          script: |
            const projectId = '${{ steps.vercel_deploy.outputs.vercel_project_id }}';
            const repoName = '${{ steps.criar_repo.outputs.REPO_NAME }}';
            const repoFullName = `${{ github.repository_owner }}/${repoName}`;
            
            const buildCommand = '${{ steps.framework_config.outputs.BUILD_COMMAND }}';
            const outputDirectory = '${{ steps.framework_config.outputs.OUTPUT_DIRECTORY }}';
            const installCommand = '${{ steps.framework_config.outputs.INSTALL_COMMAND }}';
            const framework = '${{ steps.framework_config.outputs.FRAMEWORK }}';
            
            const updateConfig = {
              gitRepository: {
                type: 'github',
                repo: repoFullName,
                productionBranch: 'prd'
              },
              buildCommand: buildCommand,
              installCommand: installCommand,
              framework: framework
            };
            
            // Só adiciona outputDirectory se não estiver vazio
            if (outputDirectory) {
              updateConfig.outputDirectory = outputDirectory;
            }
            
            // Configurar branch 'prd' como branch de produção
            const updateResponse = await fetch(`https://api.vercel.com/v9/projects/${projectId}`, {
              method: 'PATCH',
              headers: {
                'Authorization': `Bearer ${process.env.VERCEL_TOKEN}`,
                'Content-Type': 'application/json',
                ...(process.env.VERCEL_ORG_ID && { 'X-Vercel-Team-Id': process.env.VERCEL_ORG_ID })
              },
              body: JSON.stringify(updateConfig)
            });
            
            if (updateResponse.ok) {
              const updatedProject = await updateResponse.json();
              console.log('✅ Projeto atualizado com branch "prd" como produção');
              console.log(`✅ Configurações do ${framework.toUpperCase()} aplicadas`);
            } else {
              const error = await updateResponse.text();
              console.warn('⚠️ Resposta da atualização:', error);
              
              // Tentar abordagem alternativa usando settings
              const settingsResponse = await fetch(`https://api.vercel.com/v1/projects/${projectId}/settings`, {
                method: 'PATCH',
                headers: {
                  'Authorization': `Bearer ${process.env.VERCEL_TOKEN}`,
                  'Content-Type': 'application/json',
                  ...(process.env.VERCEL_ORG_ID && { 'X-Vercel-Team-Id': process.env.VERCEL_ORG_ID })
                },
                body: JSON.stringify({
                  productionBranch: 'prd'
                })
              });
              
              if (settingsResponse.ok) {
                console.log('✅ Branch "prd" configurada como produção (método alternativo)');
              } else {
                console.warn('⚠️ Não foi possível configurar branch de produção automaticamente');
                console.log('ℹ️ Você pode configurar manualmente na dashboard da Vercel');
              }
            }

      - name: Configurar webhooks e proteções do repositório
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GHUB_TOKEN }}
          script: |
            const repoName = '${{ steps.criar_repo.outputs.REPO_NAME }}';
            
            try {
              // Configurar branch protection para prd (não para main)
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: repoName,
                branch: 'prd',
                required_status_checks: {
                  strict: false,
                  contexts: []
                },
                enforce_admins: false,
                required_pull_request_reviews: null,
                restrictions: null,
                allow_force_pushes: true,
                allow_deletions: false
              });
              
              console.log('✅ Branch protection configurada para "prd"');
            } catch (error) {
              console.log('⚠️ Branch protection não configurada:', error.message);
            }

      - name: Criar resumo do projeto
        run: |
          echo "## 🚀 Projeto Criado com Sucesso!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📋 Detalhes do Projeto:" >> $GITHUB_STEP_SUMMARY
          echo "- **Nome:** ${{ steps.criar_repo.outputs.REPO_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Tipo:** ${{ github.event.inputs.tipo }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Empresa:** ${{ github.event.inputs.empresa }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Nome Vercel:** ${{ github.event.inputs.nome_vercel }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Framework:** ${{ github.event.inputs.framework }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Repositório:** [GitHub](https://github.com/${{ github.repository_owner }}/${{ steps.criar_repo.outputs.REPO_NAME }})" >> $GITHUB_STEP_SUMMARY
          echo "- **Site Vercel:** [${{ steps.vercel_deploy.outputs.vercel_url }}](${{ steps.vercel_deploy.outputs.vercel_url }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### ⚙️ Configurações Vercel:" >> $GITHUB_STEP_SUMMARY
          echo "- **Framework:** ${{ steps.framework_config.outputs.FRAMEWORK }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Command:** ${{ steps.framework_config.outputs.BUILD_COMMAND }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Output Directory:** ${{ steps.framework_config.outputs.OUTPUT_DIRECTORY }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Install Command:** ${{ steps.framework_config.outputs.INSTALL_COMMAND }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch de Produção:** prd" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🔧 Comandos Personalizados:" >> $GITHUB_STEP_SUMMARY
          if [ -n "${{ github.event.inputs.build_command }}" ]; then
            echo "- ✅ Build customizado: \`${{ github.event.inputs.build_command }}\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "- 📋 Build padrão usado" >> $GITHUB_STEP_SUMMARY
          fi
          if [ -n "${{ github.event.inputs.output_directory }}" ]; then
            echo "- ✅ Output customizado: \`${{ github.event.inputs.output_directory }}\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "- 📋 Output padrão usado" >> $GITHUB_STEP_SUMMARY
          fi
          if [ -n "${{ github.event.inputs.install_command }}" ]; then
            echo "- ✅ Install customizado: \`${{ github.event.inputs.install_command }}\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "- 📋 Install padrão usado" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📝 Próximos passos:" >> $GITHUB_STEP_SUMMARY
          echo "1. 📁 Adicione seus arquivos no repositório" >> $GITHUB_STEP_SUMMARY
          echo "2. 🔄 Faça commit e push para a branch **prd**" >> $GITHUB_STEP_SUMMARY
          echo "3. 🚀 O deploy automático será disparado na Vercel" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "⚠️ **Importante:** Deploy automático acontece apenas na branch **prd**, não na main!"