name: Criar Repositório Único

on:
  workflow_dispatch:
    inputs:
      tipo:
        description: 'Tipo do projeto (site ou lp)'
        required: true
        default: 'site'
      empresa:
        description: 'Nome da empresa/projeto'
        required: true

jobs:
  criar:
    runs-on: ubuntu-latest

    steps:
      - name: Criar Repositório
        run: |
          PREFIX="${{ github.event.inputs.tipo }}-${{ github.event.inputs.empresa }}"
          node scripts/criar-repos.js "$PREFIX" "${{ github.event.inputs.tipo }}"
        env:
          GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
